### ISSUE TITLE
Recognition property path with multiple periods causing issues in nameMapping.d.ts file

### ISSUE THREAD

**Issue by fmc91** [deitry/vscode-testcomplete#2]
Hi

I am just starting out with the TestComplete extension for VSCode.

One of my colleagues, in their wisdom, has decided to use the LabelControl.Text.OleValue as a recognition property for a mapped object.

I've noticed that when the property path contains a single period, this is converted to an underscore in the nameMapping.d.ts file. For example, LabelControl.Text becomes 'LabelControl_Text'. However, when there are multiple periods, only the first one is converted, so the above example becomes 'Label_Control.Text'. This isn't a valid TS property name, so when it appears, it causes knock-on syntax errors in the remainder of the file, causing the whole thing to be unusable.

![image](https://user-images.githubusercontent.com/68566145/157228526-44f04383-fb37-401e-a1eb-987006a5e060.png)

For now, I have commented out the offending properties, but a fix would be ideal.

**Comment by deitry** [comment]
Now dotted properties should be generated as child objects.
https://github.com/deitry/vscode-testcomplete/commit/3476abe2fb70f5e5d1c0a25ce32c75014a47ac4a

Please check new 0.0.6 version.

**Comment by fmc91** [comment]
Hi
Many thanks for your swift reply.
I have updated to the latest version, but unfortunately, the nameMapping.d.ts file is not being updated.
I tried running the 'TestComplete: Generate project-related modules' command again, but nothing happened.
I found that the tsconfig.json file is still referring to the {User}/.vscode/extensions/deitry.vscode-testcomplete-0.0.5 folder. I changed this to 0.0.6 and tried to run the command again, but it still did nothing.
I tried deleting the .vscode/.tc folder and running the command, but again, nothing happens, and I am not seeing any messages in the output panel.
I tried running the command for a new project, and it generates the files in .vscode/.tc but TestComplete built-in types and variables are now not being recognised.
I can't seem to locate the {User}/.vscode/extensions/deitry.vscode-testcomplete-0.0.6/testcomplete-ts-api/api/*.d.ts file that is referred to in the tsconfig.json file.
This is all I have in the deitry.vscode-testcomplete-0.0.6 folder:
![image](https://user-images.githubusercontent.com/68566145/157418184-3fd97d91-e14d-4bd9-b985-08ab907e041f.png)

**Comment by deitry** [comment]
Whoops. I published extension from new workspace folder and forgot to checkout [testcomplete-ts-api](https://github.com/deitry/testcomplete-ts-api) submodule, so it was not included into vsix package.

As for path update let me check a bit since it should work. Maybe it was not updated due to same missing folder

**Comment by deitry** [comment]
I pushed 0.0.7 with testcomplete-ts-api, it should be already available.

Also I checked path update, in my case both `Project/Script/jsconfig.json` and `.vscode/.tc/Project/tsconfig.json` become updated after new version is installed. 

To make manual js/tsconfig regeneration, you can try to run `TestComplete: Initialize support` command. Please note that `TestComplete: Generate project-related modules` do not changes these files.
